version: '3.8'

services:
  app:
    build: ./server
    restart: always
    ports:
      - "${APP_PORT:-9010}:3001"
    environment:
      - DATABASE_URL=postgres://appuser:${DB_PASSWORD:-dbpass_test}@db:5432/${DB_NAME:-sprachen_db_test}
      - JWT_SECRET=${JWT_SECRET:-#!Alex2019_TEST_ONLY}
      - NODE_ENV=production
      # --- E-Mail (SMTP) Einstellungen via GMX ---
      - SMTP_HOST=mail.gmx.net
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=christian.bernauer@imail.de
      - SMTP_PASS=Gmxsindbadistvega#1160
    depends_on:
      - db
#    volumes:
#      - ./server/public:/app/public

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=${DB_PASSWORD:-dbpass_test}
      - POSTGRES_DB=${DB_NAME:-sprachen_db_test}
    ports:
      - "${DB_PORT:-5435}:5432"
    volumes:
      - sprachen_db_data:/var/lib/postgresql/data

volumes:
  sprachen_db_data:
    # Hinweis: Falls du ein externes Volume nutzt, stelle sicher, dass es existiert.
    # Hier nutzen wir nun ein Standard-Volume für die Testumgebung.
