# Docker Compose for Multi-Language App

services:
  app:
    build: ./server
    restart: always
    ports:
      - "${APP_PORT:-9011}:3001"
    environment:
      - DATABASE_URL=postgres://appuser:${DB_PASSWORD:-dbpass_test}@db:5432/${DB_NAME:-italian_db_test}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      # --- E-Mail (SMTP) Einstellungen via GMX ---
      - SMTP_HOST=mail.gmx.net
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=christian.bernauer@imail.de
      - SMTP_PASS=${SMTP_PASS}
      - APP_URL=${APP_URL:-https://vokabeln.bernauer24.com}
      - OIDC_ISSUER_URL=${OIDC_ISSUER_URL:-}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:-}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET:-}
    depends_on:
      - db
#    volumes:
#      - ./server/public:/app/public

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=${DB_PASSWORD:-dbpass_test}
      - POSTGRES_DB=${DB_NAME:-italian_db_test}
    ports:
      - "${DB_PORT:-5436}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
