version: '3.8'

services:
  app:
    build: ./server
    restart: always
    ports:
      - "${APP_PORT:-9009}:3001"
    environment:
      - DATABASE_URL=postgres://appuser:${DB_PASSWORD:-dbpass_test}@db:5432/${DB_NAME:-italian_db_test}
      - JWT_SECRET=${JWT_SECRET:-#!Alex2019_TEST_ONLY}
      - NODE_ENV=production
      # --- E-Mail (SMTP) Einstellungen via GMX ---
      - SMTP_HOST=mail.gmx.net
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=christian.bernauer@imail.de
      - SMTP_PASS=Gmxsindbadistvega#1160
    depends_on:
      - db
    volumes:
      - ./server/public:/app/public

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=${DB_PASSWORD:-dbpass_test}
      - POSTGRES_DB=${DB_NAME:-italian_db_test}
    ports:
      - "${DB_PORT:-5434}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
    external: true
    name: ${DB_VOLUME:-postgres_data}
