name: Deploy to Test Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Ermöglicht das manuelle Starten über das GitHub UI

jobs:
  deploy:
    runs-on: self-hosted  # Wichtig: Nutzt den lokalen Runner auf deinem Server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and Restart App
        run: |
          cd /home/systemv/test
          git fetch origin main
          git reset --hard origin/main
          docker-compose down --remove-orphans
          docker-compose build --no-cache
          docker-compose up -d --force-recreate --remove-orphans
