name: Deploy to Test Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and Restart App (Test)
        run: |
          mkdir -p /home/systemv/multilang-test
          cd /home/systemv/multilang-test
          
          if [ ! -d ".git" ]; then
            git clone https://github.com/boernie77/Sprachenapp-Englisch-Italienisch.git .
          fi
          
          git fetch origin main
          git reset --hard origin/main
          
          docker-compose down --remove-orphans
          docker-compose build --no-cache
          docker-compose up -d --force-recreate --remove-orphans
